# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-microservice-deployment
  labels:
    app: nodejs-microservice
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: nodejs-microservice
  template:
    metadata:
      labels:
        app: nodejs-microservice
    spec:
      containers:
        - name: nodejs-microservice
          image: capstoneacrsamb.azurecr.io/nodejs-microservice:{{GITHUB_SHA}}

          ports:
            - containerPort: 3000  # Port your application listens on
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 20
